import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="min-h-screen  p-20 text-blue-800">
          <p className="text-9xl mt-64"></p>
        </div>


        <nav className="fixed bottom-0 inset-x-0 bg-blue-100 flex justify-between text-sm text-blue-900 titlecase ">
          <a href="#" className="w-full block py-5 px-3 text-center hover:bg-blue-200 hover:text-blue-800 transition duration-300">

            Channels
          </a>

          <a href="#" className="w-full block py-5 px-3 text-center hover:bg-blue-200 hover:text-blue-800">
            Activity
          </a>

          <a href="#" className="w-full block py-5 px-3 text-center hover:bg-blue-200 hover:text-blue-800">
            Control
          </a>

          <a href="#" className="w-full block py-5 px-3 text-center hover:bg-blue-200 hover:text-blue-800">

            Settings
          </a>

        </nav>
      </main>
    </div>
  )
}
